/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as CatalogoProductIdRouteImport } from './routes/catalogo.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoProductIdRoute = CatalogoProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CatalogoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/usuarios': typeof UsuariosRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/usuarios': typeof UsuariosRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRouteWithChildren
  '/pedidos': typeof PedidosRoute
  '/usuarios': typeof UsuariosRoute
  '/catalogo/$productId': typeof CatalogoProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/catalogo' | '/pedidos' | '/usuarios' | '/catalogo/$productId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/catalogo' | '/pedidos' | '/usuarios' | '/catalogo/$productId'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/pedidos'
    | '/usuarios'
    | '/catalogo/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRouteWithChildren
  PedidosRoute: typeof PedidosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo/$productId': {
      id: '/catalogo/$productId'
      path: '/$productId'
      fullPath: '/catalogo/$productId'
      preLoaderRoute: typeof CatalogoProductIdRouteImport
      parentRoute: typeof CatalogoRoute
    }
  }
}

interface CatalogoRouteChildren {
  CatalogoProductIdRoute: typeof CatalogoProductIdRoute
}

const CatalogoRouteChildren: CatalogoRouteChildren = {
  CatalogoProductIdRoute: CatalogoProductIdRoute,
}

const CatalogoRouteWithChildren = CatalogoRoute._addFileChildren(
  CatalogoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRouteWithChildren,
  PedidosRoute: PedidosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
